### PR TITLE
Review all doc pages before tagging v3

### LINKED ISSUE #867: Improve documentation on CCL MG param handling.
I'm finding that as of recently, it seems like changing the value of mu0 doesn't change the matter power spectrum. Here's a pdf of a notebook where I demonstrate that changing this parameter seems to have no effect at all on the linear matter power spectrum.
[check_mg_functionality.pdf](https://github.com/LSSTDESC/CCL/files/6213270/check_mg_functionality.pdf)

What's going on here? mu0 should definitely change the linear matter power spectrum, right? Am I missing something big?

@damonge @mishakb any ideas?

(My project student @OSmotherly initially identified this behaviour so I'm tagging him so that he can follow.)

### LINKED ISSUE #871: Link equations to functions in docs
A suggestion I received: It would be good to make it clear which functions correspond to which equations in the docs. For example, can we give equations for each function here? https://ccl.readthedocs.io/en/latest/api/pyccl.correlations.html

### LINKED ISSUE #1091: Bug: `angular_cl_cov_SSC` and `angular_cl_cov_cNG` do not accept `None` for `tkka` argument
Contrary to what reported in the [documentation](https://ccl.readthedocs.io/en/latest/api/pyccl.core.html#pyccl.core.Cosmology.angular_cl_cov_SSC), the `angular_cl_cov_SSC` and `angular_cl_cov_cNG` functions do not accept `None` as value for the `tkka` argument. Moreover, the formula in the documentation is exactly the same (including the cNG subscript in the left hand side). PyCCL version: 2.8.0

This is the error:

```
    tsp = t_of_kk_a.tsp
AttributeError: 'NoneType' object has no attribute 'tsp'
```

PS if indeed these covariance functions do not accept `None` as input value, in the case of number counts should I pass the `tkka` computed with `HaloProfileHOD`? 
```
import pyccl as ccl
halo_profile = ccl.halos.profiles.HaloProfileHOD(c_M_relation=c_M_relation)
tkka = ccl.halos.halo_model.halomod_Tk3D_SSC(cosmo, hmc, prof1=halo_profile, ...)
```

because when calling `HaloProfileHOD` I get the error
```
/opt/anaconda3/lib/python3.9/site-packages/pyccl/halos/pk_4pt.py:518:
RuntimeWarning: invalid value encountered in true_divide
dpk12[ia] = ((47/21 - dpk/3)*i11_1*i11_2*pk + i12_12) / (norm1 * norm2)
```

### PR DESCRIPTION
**Pull request by damonge**
We need to review all of the doc pages on readthedocs, since some of them are a bit antiquated, and some of the autodoc pages show small typos/inaccuracies. This is the last thing to do before we're able to tag v3!

A few instructions for reviewers:
- Virtually no code has changed. I've marked below in comments the only places where this has happened, which had to do with things that had been deprecated long ago but which I only noticed while going through the documentation. Besides this, I don't think it's worth looking at the code itself.
- The most efficient way to review this PR would be to have a systematic look at the documentation pages. I've activated them for this branch here: https://ccl.readthedocs.io/en/doc_review/. I would thus suggest reviewers to look at the doc pages and flag issues as comments here, rather than looking at the code itself.

Of course, reviewers should feel free to proceed as they prefer!

Closes #1091
Closes #867
Closes #871

### CODE REVIEW

**Comment by hsinfan1996** [comment]
Update this line?
https://github.com/LSSTDESC/CCL/blob/11375ea2a2329c9c7332fa2aacdb192a5dbfa09d/readthedocs/conf.py#L97

**Comment by hsinfan1996** [comment]
The link is outdated. Should be https://www.numpy.org/
https://github.com/LSSTDESC/CCL/blob/11375ea2a2329c9c7332fa2aacdb192a5dbfa09d/readthedocs/conf.py#L229

File: include/ccl_core.h [hunk 1]
```diff
@@ -182,14 +177,6 @@ typedef struct ccl_gsl_params {
...
   double EPS_SCALEFAC_GROWTH;
 
-  // halo model
-  double HM_MMIN;
-  double HM_MMAX;
-  double HM_EPSABS;
-  double HM_EPSREL;
-  size_t HM_LIMIT;
-  int HM_INT_METHOD;
-
```
Comment (damonge) [inline include/ccl_core.h:192]: Code change. These variables were not used anymore.

File: pyccl/_core/parameters/fftlog_params.py [hunk 2]
```diff
@@ -52,7 +52,7 @@ def __repr__(self):
     def __eq__(self, other):
         if self is other:
             True
-        if type(self) != type(other):
+        if type(self) is not type(other):
```
Comment (damonge) [inline pyccl/_core/parameters/fftlog_params.py:55]: Code change. flake8 flagged this as more appropriate. It does the same thing as before.

File: pyccl/cosmology.py [hunk 3]
```diff
@@ -35,7 +47,6 @@ class TransferFunctions(Enum):
 class MatterPowerSpectra(Enum):
     LINEAR = "linear"
     HALOFIT = "halofit"
-    HALOMODEL = "halomodel"
```
Comment (damonge) [inline pyccl/cosmology.py:38]: Code change. This was not supported anymore.

File: pyccl/tests/test_cosmology.py [hunk 4]
```diff
@@ -219,20 +219,21 @@ def test_pyccl_default_params():
     """Check that the Python-layer for setting the gsl and spline parameters
     works on par with the C-layer.
     """
-    HM_MMIN = ccl.gsl_params["HM_MMIN"]
+    EPS_SCALEFAC_GROWTH = ccl.gsl_params["EPS_SCALEFAC_GROWTH"]
```
Comment (damonge) [inline pyccl/tests/test_cosmology.py:222]: Code change. This is to avoid using deprecated C-level variables in tests.

**Comment by hsinfan1996** [comment]
A more detailed table of contents for `API Documentation` would be great, e.g. 
image

**Comment by hsinfan1996** [comment]
Is there a reason to use this specific version of sphinx_rtd_theme?
https://github.com/LSSTDESC/CCL/blob/b4fbaa74d76f04e7ea63071dcb008c7eb68ed163/readthedocs/requirements.txt#L6

**Comment by hsinfan1996** [comment]
> @hsinfan1996 a few months ago the default rtd theme had a few bugs that affected how some things were displayed. We could check if this is now fixed.
> 
> Regarding the TOC: do you have a `conf.py` showing how to do this somewhere?

conf.py from CLMM
https://github.com/LSSTDESC/CLMM/blob/c6cf806cd9b542f7286187ed0ecb6432f959a767/docs/conf.py#L216-L229

**Comment by hsinfan1996** [comment]
> > @hsinfan1996 a few months ago the default rtd theme had a few bugs that affected how some things were displayed. We could check if this is now fixed.
> > Regarding the TOC: do you have a `conf.py` showing how to do this somewhere?
> 
> conf.py from CLMM https://github.com/LSSTDESC/CLMM/blob/c6cf806cd9b542f7286187ed0ecb6432f959a767/docs/conf.py#L216-L229

@damonge Turned out it is just a `html_theme_options` to be added in the conf.py. No need to modify any .rst files.

**Comment by anicola** [comment]
I have started going through the top-level docs and just found these super small things. I will now start going through the function docs. 
image
image
image

File: readthedocs/conf.py [hunk 5]
```diff
@@ -132,7 +134,11 @@ def __getattr__(cls, name):
 #
 
 html_theme = "sphinx_rtd_theme"
-html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
+html_theme_options = {
+    "collapse_navigation": False,
+    "titles_only": True,
+}
+# html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
```
Comment (hsinfan1996) [inline readthedocs/conf.py:141]: I disabled this line to make the `API documentation` expandable by clicking the + sign. Need to test if there are any side effects.

Comment (hsinfan1996) [reply readthedocs/conf.py:141]: CLMM does not have this line and everything works fine.

**Comment by hsinfan1996** [comment]
I removed modules.rst so the TOC looks like
image
instead of
image

I can revert it if anyone wants pyccl package to be the first level.

**Comment by damonge** [comment]
This looks good. Thanks @hsinfan1996 !

**Comment by damonge** [comment]
Thanks a lot @anicola , super useful! Just fixed those.
